AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin-recon specific exceptions
#

# Empty classes
Lint/EmptyClass:
  Exclude:
    - 'lib/ronin/recon/value.rb'
    - 'lib/ronin/recon/message/shutdown.rb'

# Allow Value classes to not call super() in their initialize
Lint/MissingSuper:
  Exclude:
    - 'lib/ronin/recon/values/*.rb'

# Worker#initialize exists for documentation purposes
Lint/UselessMethodDefinition:
  Exclude:
    - 'lib/ronin/recon/worker.rb'

# until is better suited for waiting until the Engine is "empty"
Style/WhileUntilModifier:
  Exclude:
    - 'lib/ronin/recon/engine.rb'

# the Values #=== methods need to compare the other value's class
Style/ClassEqualityComparison:
  Exclude:
    - 'lib/ronin/recon/values/*.rb'

# must use #=== to compare values
Style/CaseEquality:
  Exclude:
    - 'lib/ronin/recon/scope.rb'
    - 'lib/ronin/recon/values/ip_range.rb'
    - 'spec/**/*_spec.rb'
